# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'overview.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be los
from add_manager import Ui_AddManager as addManager
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from see_moviedet import seeMovieDetFrame
from send_gift import Ui_sendGiftFrame
class Ui_AdminPanel(object):
    def openaddmanager(self):
        self.addMangerOpen = QFrame()
        self.ui = addManager()
        self.ui.setupUi(self.addMangerOpen)
        self.addMangerOpen.show()
    def openmovdet(self):
        self.movdetOpen = QFrame()
        self.ui = seeMovieDetFrame()
        self.ui.setupUi(self.movdetOpen)
        self.movdetOpen.show()
    def opensendgift(self):
        self.sendgiftOpen = QFrame()
        self.ui = Ui_sendGiftFrame()
        self.ui.setupUi(self.sendgiftOpen)
        self.sendgiftOpen.show()
    def setupUi(self, AdminPanel):
        AdminPanel.setObjectName("AdminPanel")
        AdminPanel.resize(947, 574)
        AdminPanel.setFixedSize(821,547)
        AdminPanel.setBaseSize(QtCore.QSize(800, 500))
        font = QtGui.QFont()
        font.setPointSize(14)
        AdminPanel.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/res/811804_cinema_512x512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AdminPanel.setWindowIcon(icon)
        self.Main = QtWidgets.QWidget(AdminPanel)
        self.Main.setObjectName("Main")
        self.options_list = QtWidgets.QListWidget(self.Main)
        self.options_list.setGeometry(QtCore.QRect(700, 0, 121, 571))
        self.options_list.setObjectName("options_list")
        self.addMangerlabel = QtWidgets.QLabel(self.Main)
        self.addMangerlabel.setGeometry(QtCore.QRect(710, 140, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Niagara Solid")
        font.setPointSize(15)
        self.addMangerlabel.setFont(font)
        self.addMangerlabel.setObjectName("addMangerlabel")
        self.addManagerbtn = QtWidgets.QPushButton(self.Main)
        self.addManagerbtn.setGeometry(QtCore.QRect(730, 80, 51, 51))
        self.addManagerbtn.setStyleSheet("background-image: url(:/newPrefix/res/user.png);")
        self.addManagerbtn.setText("")
        self.addManagerbtn.setObjectName("addManagerbtn")
        self.addManagerbtn.clicked.connect(self.openaddmanager)
        self.seeMovDetbtn = QtWidgets.QPushButton(self.Main)
        self.seeMovDetbtn.setGeometry(QtCore.QRect(730, 210, 51, 51))
        self.seeMovDetbtn.setStyleSheet("background-image: url(:/newPrefix/res/movdet.png);")
        self.seeMovDetbtn.setText("")
        self.seeMovDetbtn.setObjectName("seeMovDetbtn")
        self.seeMovDetbtn.clicked.connect(self.openmovdet)
        self.movDetailsLabel = QtWidgets.QLabel(self.Main)
        self.movDetailsLabel.setGeometry(QtCore.QRect(720, 280, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Niagara Solid")
        font.setPointSize(15)
        self.movDetailsLabel.setFont(font)
        self.movDetailsLabel.setObjectName("movDetailsLabel")
        self.mailbtn = QtWidgets.QPushButton(self.Main)
        self.mailbtn.setGeometry(QtCore.QRect(730, 340, 51, 51))
        self.mailbtn.setStyleSheet("background-image: url(:/newPrefix/res/mail.png);")
        self.mailbtn.setText("")
        self.mailbtn.setObjectName("mailbtn")
        self.mailbtn.clicked.connect(self.opensendgift)
        self.mainLabel = QtWidgets.QLabel(self.Main)
        self.mainLabel.setGeometry(QtCore.QRect(730, 410, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Niagara Solid")
        font.setPointSize(15)
        self.mainLabel.setFont(font)
        self.mainLabel.setObjectName("mainLabel")
        self.managerList = QtWidgets.QListWidget(self.Main)
        self.managerList.setGeometry(QtCore.QRect(-20, 100, 131, 341))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.managerList.sizePolicy().hasHeightForWidth())
        self.managerList.setSizePolicy(sizePolicy)
        self.managerList.setObjectName("managerList")
        self.ManagerHeading = QtWidgets.QLabel(self.Main)
        self.ManagerHeading.setGeometry(QtCore.QRect(14, 40, 81, 31))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(12)
        self.ManagerHeading.setFont(font)
        self.ManagerHeading.setObjectName("ManagerHeading")
        self.MainLabel = QtWidgets.QLabel(self.Main)
        self.MainLabel.setGeometry(QtCore.QRect(0, 0, 701, 571))
        self.MainLabel.setStyleSheet("background-image: url(:/newPrefix/res/2-movies-flat-icons-square.jpg);")
        self.MainLabel.setText("")
        self.MainLabel.setObjectName("MainLabel")
        self.AdminPanelOverlay = QtWidgets.QLabel(self.Main)
        self.AdminPanelOverlay.setGeometry(QtCore.QRect(180, 40, 481, 491))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.AdminPanelOverlay.setFont(font)
        self.AdminPanelOverlay.setStyleSheet("background-color: rgba(255, 255, 255, 170);\n"
"\n"
"")
        self.AdminPanelOverlay.setText("")
        self.AdminPanelOverlay.setObjectName("AdminPanelOverlay")
        self.AdminHeading = QtWidgets.QLabel(self.Main)
        self.AdminHeading.setGeometry(QtCore.QRect(280, 50, 291, 41))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(34)
        self.AdminHeading.setFont(font)
        self.AdminHeading.setObjectName("AdminHeading")
        self.NameLabel = QtWidgets.QLabel(self.Main)
        self.NameLabel.setGeometry(QtCore.QRect(250, 160, 51, 31))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(16)
        self.NameLabel.setFont(font)
        self.NameLabel.setObjectName("NameLabel")
        self.loginIconLabel = QtWidgets.QLabel(self.Main)
        self.loginIconLabel.setGeometry(QtCore.QRect(530, 130, 101, 101))
        self.loginIconLabel.setStyleSheet("background-image: url(:/newPrefix/res/login icon.png);")
        self.loginIconLabel.setText("")
        self.loginIconLabel.setObjectName("loginIconLabel")
        self.adminNameEdit = QtWidgets.QLineEdit(self.Main)
        self.adminNameEdit.setGeometry(QtCore.QRect(320, 160, 201, 31))
        self.adminNameEdit.setObjectName("adminNameEdit")
        self.adminEmailLabel = QtWidgets.QLabel(self.Main)
        self.adminEmailLabel.setGeometry(QtCore.QRect(240, 230, 71, 31))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(16)
        self.adminEmailLabel.setFont(font)
        self.adminEmailLabel.setObjectName("adminEmailLabel")
        self.adminEmailEdit = QtWidgets.QLineEdit(self.Main)
        self.adminEmailEdit.setGeometry(QtCore.QRect(320, 230, 201, 31))
        self.adminEmailEdit.setObjectName("adminEmailEdit")
        self.adminContactLabel = QtWidgets.QLabel(self.Main)
        self.adminContactLabel.setGeometry(QtCore.QRect(210, 300, 91, 31))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(16)
        self.adminContactLabel.setFont(font)
        self.adminContactLabel.setObjectName("adminContactLabel")
        self.adminContactEdit = QtWidgets.QLineEdit(self.Main)
        self.adminContactEdit.setGeometry(QtCore.QRect(320, 300, 201, 31))
        self.adminContactEdit.setObjectName("adminContactEdit")
        self.EditAdminbtn = QtWidgets.QPushButton(self.Main)
        self.EditAdminbtn.setGeometry(QtCore.QRect(200, 110, 31, 31))
        self.EditAdminbtn.setStyleSheet("background-image: url(:/newPrefix/res/edit.png);")
        self.EditAdminbtn.setText("")
        self.EditAdminbtn.setObjectName("EditAdminbtn")
        self.managerSidebarLabel = QtWidgets.QLabel(self.Main)
        self.managerSidebarLabel.setGeometry(QtCore.QRect(-4, 2, 114, 437))
        self.managerSidebarLabel.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(12)
        self.managerSidebarLabel.setFont(font)
        self.managerSidebarLabel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.managerSidebarLabel.setText("")
        self.managerSidebarLabel.setObjectName("managerSidebarLabel")
        self.hiddenSavebtn = QtWidgets.QPushButton(self.Main)
        self.hiddenSavebtn.setGeometry(QtCore.QRect(380, 370, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.hiddenSavebtn.setFont(font)
        self.hiddenSavebtn.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.hiddenSavebtn.setText("")
        self.hiddenSavebtn.setObjectName("hiddenSavebtn")
        self.options_list.raise_()
        self.addMangerlabel.raise_()
        self.movDetailsLabel.raise_()
        self.addManagerbtn.raise_()
        self.seeMovDetbtn.raise_()
        self.mailbtn.raise_()
        self.mainLabel.raise_()
        self.MainLabel.raise_()
        self.AdminPanelOverlay.raise_()
        self.AdminHeading.raise_()
        self.NameLabel.raise_()
        self.loginIconLabel.raise_()
        self.adminNameEdit.raise_()
        self.adminEmailLabel.raise_()
        self.adminEmailEdit.raise_()
        self.adminContactLabel.raise_()
        self.adminContactEdit.raise_()
        self.EditAdminbtn.raise_()
        self.managerSidebarLabel.raise_()
        self.managerList.raise_()
        self.ManagerHeading.raise_()
        self.hiddenSavebtn.raise_()
        AdminPanel.setCentralWidget(self.Main)

        self.retranslateUi(AdminPanel)
        QtCore.QMetaObject.connectSlotsByName(AdminPanel)

    def retranslateUi(self, AdminPanel):
        _translate = QtCore.QCoreApplication.translate
        AdminPanel.setWindowTitle(_translate("AdminPanel", "Admin panel"))
        self.addMangerlabel.setText(_translate("AdminPanel", "Add/update manager"))
        self.movDetailsLabel.setText(_translate("AdminPanel", "See Movie details"))
        self.mainLabel.setText(_translate("AdminPanel", "send a mail"))
        self.ManagerHeading.setText(_translate("AdminPanel", "MANAGERS"))
        self.AdminHeading.setText(_translate("AdminPanel", "ADMIN PANEL"))
        self.NameLabel.setText(_translate("AdminPanel", "NAME"))
        self.adminEmailLabel.setText(_translate("AdminPanel", "Email"))
        self.adminContactLabel.setText(_translate("AdminPanel", "Contact"))

import myresources_rc
import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AdminPanel = QtWidgets.QMainWindow()
    ui = Ui_AdminPanel()
    ui.setupUi(AdminPanel)
    AdminPanel.show()
    sys.exit(app.exec_())

